INSERT INTO APPLICANT_BASIC_INFO (FNAME, LNAME) VALUES 'Pratik', 'Chavan');
INSERT INTO APPLICANT_BASIC_INFO (FNAME, LNAME) VALUES ('Shubham', 'Vengurlekar');
INSERT INTO APPLICANT_BASIC_INFO (FNAME, LNAME) VALUES ('Bhramesh', 'Varia');
INSERT INTO APPLICANT_BASIC_INFO (FNAME, LNAME) VALUES ('Sarvesh', 'Bhosle');
INSERT INTO APPLICANT_BASIC_INFO (FNAME, LNAME) VALUES ('Rahul', 'Sogam');